### ISSUE TITLE
citizen voting age population Census Variable is wrong

### ISSUE THREAD

**Issue by yifeitung** [kuriwaki/ccesMRPprep#7]
Hi @kuriwaki ,

For the `get_acs_cvap()` function, I think the Census variable code you chose are wrong. Citizen Voting Age population should be native or naturalized citizens aged 18 or above. Therefore, it should be the total of `009`, `011`, `020`, `022` for each race category instead of the total of `004`, `006`, `015`, and `017`.  Please check them again. 

Let me know if I am wrong.

Thank you!

**Comment by kuriwaki** [comment]
Thanks @yifeitung, you are correct. I have made the fix in the new version (0.1.8.1). If you notice any other ACS datasets in which this coding does not hold (as well as anything else on the package), please let me know.
